# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

pool:
  vmImage: ubuntu-latest

steps:
- task: TerraformCLI@0
  displayName: Terraform init
  inputs:
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/ACR'
    allowTelemetryCollection: false
- task: TerraformCLI@0
  displayName: Terraform Plan
  inputs:
    command: 'plan'
    workingDirectory: '$(System.DefaultWorkingDirectory)/ACR'
    environmentServiceName: 'kubeterra'
    allowTelemetryCollection: false
- task: TerraformCLI@0
  displayName: Terraform Apply
  inputs:
    command: 'apply'
    workingDirectory: '$(System.DefaultWorkingDirectory)/ACR'
    environmentServiceName: 'kubeterra'
    allowTelemetryCollection: false


